spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 2GB
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${waitfall.mysql.host}:${waitfall.mysql.port}/${waitfall.mysql.database}?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: ${waitfall.mysql.username}
    password: ${waitfall.mysql.password}
    hikari:
      connection-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 300000
      pool-name: DataSourceHikariCP
      max-lifetime: 600000
      connection-test-query: select 1
      validation-timeout: 30000
  data:
    redis:
      repositories:
        enabled: false
      database: ${waitfall.redis.database}
      host: ${waitfall.redis.host}
      port: ${waitfall.redis.port}
      password: ${waitfall.redis.password}
      client-type: lettuce
      lettuce:
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1ms
            min-idle: 0
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1
server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
knife4j:
  enable: false
  setting:
    language: zh-CN
minio:
  endpoint: ${waitfall.minio.endpoint}
  bucketName: ${waitfall.minio.bucketName}
  secret-key: ${waitfall.minio.user}
  access-key: ${waitfall.minio.password}
auto-table:
  enable: true
  mode: update
  # 自动建数据库
  auto-build-database: true
  # 自动删除字段
  auto-drop-column: true
  # 自动删除自定义索引
  auto-drop-custom-index: true
  # 指定实体类所在包路径
  model-package: com.waitfall.*.domain.entity
  init-data:
    enable: true
    default-init-file-name: waitfall_init_data
    base-path: classpath:sql
  mysql:
    table-default-charset: utf8mb4
    table-default-collation: utf8mb4_general_ci
    column-default-charset: utf8mb4
    column-default-collation: utf8mb4_general_ci
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
easy-trans:
  #启用redis缓存 如果不用redis请设置为false
  is-enable-redis: false
  #启用全局翻译(拦截所有responseBody进行自动翻译)，如果对于性能要求很高可关闭此配置在方法上使用注解翻译
  is-enable-global: true
  #字典缓存放到redis 微服务模式请开启
  dict-use-redis: false
  # Mybatis-plus 为 3.5.3.2版本以上的3.x 版本请设置为true
  mp-new: true
token:
  jwtSecretKey: ${waitfall.token.jwtSecretKey}

sa-token:
  alone-redis:
    database: ${waitfall.sa-token.redis.database}
    host: ${waitfall.redis.host}
    port: ${waitfall.redis.port}
    password: ${waitfall.redis.password}
    client-type: lettuce
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0